### ISSUE TITLE
Weird residues above fish prompt

### ISSUE THREAD

**Issue by alexherbo2** [deadpixi/mtm#10]
I got weird residues above [fish][] prompt.

```
;fish ~;file://othala/home/alex;fish ~
```

[fish]: https://github.com/fish-shell/fish-shell

**Comment by deadpixi** [comment]
Hi @alexherbo2 

That's part of the sequence that fish prints out before the prompt when it detects it's running in a recent VTE terminal. Check your environment for a variable called "VTE_VERSION". That variable is set by the terminal emulator itself, not mtm. Because mtm is running under that terminal, it inherits its environment, including that variable.

If that variable is set, fish assumes it's running in a terminal that will support those escape sequences. mtm does not; it only handles CSR-style escape sequences (i.e. like a VT100 or eterm or eterm-color). I'm adding support for them eventually, but until then, the tail of those sequences will end up getting printed out because the escape sequence parser doesn't understand them.

I will eventually get around to adding support for the OSC-style escape sequences, which means this sort of thing will also just work with mtm.

Try setting VTE_VERSION to the empty string *before* starting fish (how you'd do that would depend on how your terminal is set up. In my (minimal) testing, that cleared up the problem.

Please try that and let me know if that works.

**Comment by alexherbo2** [comment]
It becomes:

```
;fish ~; fish ~
```

**Comment by deadpixi** [comment]
Hey @alexherbo2 

I'm just going to bite the bullet and add OSC sequence parsing to mtm. That will fix this issue as a side-effect. It'll take some time.

**Comment by alexherbo2** [comment]
Cool :)

**Comment by deadpixi** [comment]
Hi @alexherbo2 

Please check the latest code in master and let me know if it works for you.

Thanks!

**Comment by alexherbo2** [comment]
I’m using [Elvish][] now, but yeah it works.  Thanks! :)

[Elvish]: https://elvish.io
