### ISSUE TITLE
eterm issue

### ISSUE THREAD

**Issue by clasqm** [deadpixi/mtm#19]
mtm compiles on elementary os 0.4 "Loki", but then throws up an error on execution. To fix this I changed line 85 in mtm.C from

    static` const char *term = "eterm-color";

to 

    static const char *term = "Eterm-color";

works fine now.

**Comment by deadpixi** [comment]
`Eterm-color` is a different terminal (the [Enlightenment Terminal](https://github.com/billiob/terminology)) than the "eterm" that `mtm` emulates (which is the [terminal emulated by Emacs's `term.el`](https://github.com/emacs-mirror/emacs/blob/master/lisp/term.el)).

`mtm`'s terminal emulation is pretty close to that of Enlightenment Terminal (Terminology), but not quite: Terminology does back-color-erase (`bce`), and a few other things differently. 90% of the time things will work, but that 10% of the time, it won't in some irritating way.

What's probably happening is your operating system doesn't have the `eterm-color` terminfo provided. I'd recommend, instead of changing it to `Eterm-color` to either install the `eterm-color` terminfo or, even better, install `mtm`'s native terminfo using

    tic -s -x mtm.ti

and then invoking `mtm` like this:

    mtm -t mtm

**Comment by letarg0** [comment]
eterm are problem with mc
