### ISSUE TITLE
key presses not detected non x86 architecture

### ISSUE THREAD

**Issue by jp-bennett** [deadpixi/mtm#3]
I don't have a whole lot of information on this yet.  I've built mtm as a part of the Openwrt/LEDE build system, and loaded it on an MIPS router and an x86 VM.

Mtm seems to work flawlessly on the x86 VM.  On the router, it starts without issue, and the ctrl + g commands work as expected.  The enter key is handled correctly as well.  No other key strokes are detected.

The router is an ar71xx architecture, and is big-endian -- the opposite of x86.  Is it possible that mtm isn't endian safe?

I won't have much time to dig in and try to troubleshot this myself, but I'll do what I can.

**Comment by deadpixi** [comment]
Hah. I know exactly what the problem is, and honestly thought I'd noticed it and fixed it before anyone else would see it. It has to do with little-endianess and casting.

The problem basically was that at one point for the sake of brevity, mtm did this:

```c
    tmt_write(vt, (char *)&c, 1);
```

Where c was an integer. On little-endian architectures like x86/x86_64 that'll work no problem (because the character is stored in the high byte of the integer). On big-endian architectures, that'll fail because the first byte is 0 and/or sign-extended.

The other characters are handled correctly because they get caught in the handlechar routine.

At any rate, please try the latest code and let me know if it's still a problem. I'm afraid I don't have a little endian box to test on.

**Comment by jp-bennett** [comment]
Yep, that fixed it up.  I'll try to get this into the Openwrt packages repo in the next couple days, so some other people can take a look at it.

I'm curious about what features you're planning.  Two come to mind that could be very useful.  First the ability to detach and reattach.  This is super useful when ssh'd to a box, and the ssh connection drops.  The other thought that comes to mind is that it would be handy to have multiple full screen terminals that can be flipped through.
