### ISSUE TITLE
Delay when switching modes in vi

### ISSUE THREAD

**Issue by dylan-lom** [deadpixi/mtm#38]
There's a very noticable delay when switching modes in vi 

This problem exists is screen (AFAIK in tmux too), which has an option to change the escape delay: `maptimeout 0`

From the screen manpage:

> maptimeout [timeout]
>  Set the inter-character timer for input sequence detection to a timeout of timeout ms. The 
> default timeout is 300ms. Map‐
> timeout with no arguments shows the current setting.  See also "bindkey".

A quick grep through the [screen source](https://ftp.gnu.org/gnu/screen/) suggested that it is calling a `SetTimeout` function (sorry i'm not familiar enough with c to figure out any more than this)

Is there a similar option for mtm? Initial impression are really good, but i can't use it if it breaks vi :(

**Comment by deadpixi** [comment]
The ESCDELAY environment variable specifies how long to wait after pressing
escape. It's specified in milliseconds. Note that it'll need to be set
before starting mtm.

Also, pressing most keys after escape will cause the buffer to be
immediately flushed (since they don't map to a valid key sequence), so if
you start typing your command immediately after pressing escape, it should
just work.

**Comment by dylan-lom** [comment]
thanks! should've had a better look at the manual (oops)
